name: EcoWorldAuth
main: jp.minecraftuser.ecoworldauth.EcoWorldAuth
version: ${project.version}
depend: [EcoFramework]
commands:
  ewa:
    description: ewa command.
    usage: /<command> option
    permission: ecoworldauth
  ewa reload:
    description: reload ewa configuration file command.
    usage: /<command> option
    permission: ecoworldauth.reload
